#!/usr/bin/env python3
"""Generate the Betterleaks quick filter from a downloaded upstream config."""
import argparse
import hashlib
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "QuickLeak.generated.cs"
README = ROOT / "README.md"
SHA = "2a387a5bad4290a84b9a1eb679bffe70611218cc"
URL = f"https://github.com/betterleaks/betterleaks/blob/{SHA}/config/betterleaks.toml"


def update_readme_metadata(config: Path, rule_count: int) -> None:
    marker = re.compile(
        r"<!-- QUICKLEAK-METADATA:START -->.*?<!-- QUICKLEAK-METADATA:END -->",
        re.DOTALL,
    )
    current = README.read_text()
    metadata = (
        "<!-- QUICKLEAK-METADATA:START -->\n"
        f"- Betterleaks commit: `{SHA}`\n"
        f"- Downloaded config SHA-256: `{hashlib.sha256(config.read_bytes()).hexdigest()}`\n"
        f"- Generated rules: `{rule_count}`\n"
        "<!-- QUICKLEAK-METADATA:END -->"
    )
    updated = marker.sub(metadata, current, count=1)
    if updated == current:
        raise RuntimeError("README metadata markers were not found")
    README.write_text(updated)


def convert(pattern: str) -> str:
    pattern = pattern.replace("(?P<", "(?<")
    classes = {
        "alnum": "A-Za-z0-9", "alpha": "A-Za-z", "digit": "0-9",
        "lower": "a-z", "upper": "A-Z", "word": "A-Za-z0-9_",
        "space": r"\s",
    }
    return re.sub(
        r"\[\[:([a-z]+):\]\]",
        lambda match: classes.get(match.group(1), match.group(0)),
        pattern,
    )


def early_pattern(pattern: str) -> str:
    # Let token rules match the prefix and the partially entered value.
    pattern = re.sub(r"\{(\d+),(\d+)\}", r"{0,\2}", pattern)
    return re.sub(r"\{(\d+)\}", r"{0,\1}", pattern)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("config", type=Path, help="Downloaded Betterleaks TOML configuration")
parser.add_argument("--output", type=Path, default=OUT, help="Generated C# path")
args = parser.parse_args()

patch_path = ROOT / "betterleaks.toml.patch"
config = tomllib.loads(args.config.read_text())

rules = []
for rule in config["rules"]:
    if rule.get("regex"):
        pattern = convert(rule["regex"])
        rules.append(
            (rule["id"], pattern, convert(rule.get("early_regex", early_pattern(pattern))),
             tuple(keyword.lower() for keyword in rule.get("keywords", [])))
        )

if patch_path.exists():
    patch = tomllib.loads(patch_path.read_text())
    for rule in patch.get("rules", []):
        if rule.get("regex"):
            pattern = convert(rule["regex"])
            rules.append(
                (rule["id"], pattern, convert(rule.get("early_regex", early_pattern(pattern))),
                 tuple(keyword.lower() for keyword in rule.get("keywords", [])))
            )

with args.output.open("w") as output:
    output.write("// <auto-generated />\n")
    output.write(f"// Generated from Betterleaks config: {URL}\n")
    output.write(f"// Betterleaks commit: {SHA}\n")
    output.write("// Betterleaks is MIT licensed; see upstream LICENSE.\n")
    output.write("// ConsoleToSvg rules are defined in betterleaks.toml.patch.\n\n")
    output.write("using System;\nusing System.Collections.Generic;\nusing System.Collections.Frozen;\n")
    output.write("using System.Linq;\nusing System.Text.RegularExpressions;\n\n")
    output.write("namespace ConsoleToSvg.QuickLeak;\n\n")
    output.write(
        "/// <summary>Generated Betterleaks and ConsoleToSvg secret detection rules.</summary>\n"
        "public static partial class QuickLeak\n{\n"
        "    /// <summary>Associates a keyword with the generated rule that should be tested.</summary>\n"
        "    /// <param name=\"Value\">The case-insensitive keyword.</param>\n"
        "    /// <param name=\"RuleIndex\">The generated rule index.</param>\n"
        "    private readonly record struct KeywordRule(string Value, int RuleIndex);\n\n"
    )
    output.write(
        "    private static readonly FrozenDictionary<char, KeywordRule[]> KeywordIndex =\n"
        "        new Dictionary<char, KeywordRule[]>\n"
        "        {\n"
    )
    keyword_index = {}
    for index, (_, _, _, keywords) in enumerate(rules):
        for keyword in dict.fromkeys(keyword for keyword in keywords if keyword):
            keyword_index.setdefault(keyword[0], []).append((keyword, index))
    for initial, keywords in sorted(keyword_index.items()):
        values = ", ".join(
            f"new KeywordRule({json.dumps(keyword)}, {index})"
            for keyword, index in keywords
        )
        output.write(f"            [{json.dumps(initial)}[0]] = [{values}],\n")
    output.write(
        "        }.ToFrozenDictionary();\n\n"
        "    private static bool[] FindCandidateRules(string text)\n"
        "    {\n"
        f"        var candidates = new bool[{len(rules)}];\n"
        "        var textSpan = text.AsSpan();\n"
        "        for (var index = 0; index < textSpan.Length; index++)\n"
        "        {\n"
        "            if (!KeywordIndex.TryGetValue(char.ToLowerInvariant(textSpan[index]), out var keywords))\n"
        "            {\n"
        "                continue;\n"
        "            }\n"
        "            foreach (var keyword in keywords)\n"
        "            {\n"
        "                if (!candidates[keyword.RuleIndex] && textSpan[index..].StartsWith(keyword.Value, StringComparison.OrdinalIgnoreCase))\n"
        "                {\n"
        "                    candidates[keyword.RuleIndex] = true;\n"
        "                }\n"
        "            }\n"
        "        }\n"
        "        return candidates;\n"
        "    }\n\n"
        "    private static IEnumerable<QuickLeakFinding> EnumerateGeneratedRules(string text, QuickLeakScanMode mode)\n"
        "    {\n"
        "        var candidates = FindCandidateRules(text);\n"
    )
    for index, (rule_id, _, _, _) in enumerate(rules):
        output.write(
            f"        if (candidates[{index}]) foreach (Match m in (mode == QuickLeakScanMode.Early ? EarlyRule{index}() : Rule{index}()).Matches(text)) "
            f"yield return new QuickLeakFinding({json.dumps(rule_id)}, m.Index, m.Index + m.Length);\n"
        )
    output.write("    }\n\n")
    for index, (_, pattern, early, _) in enumerate(rules):
        output.write(
            f"    [GeneratedRegex({json.dumps(pattern)}, RegexOptions.CultureInvariant)]\n"
            f"    private static partial Regex Rule{index}();\n"
            f"    [GeneratedRegex({json.dumps(early)}, RegexOptions.CultureInvariant)]\n"
            f"    private static partial Regex EarlyRule{index}();\n"
        )
    output.write("}\n")

print(f"generated {len(rules)} rules")
update_readme_metadata(args.config, len(rules))
