<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <PackageId>ConsoleToSvg.Resvg</PackageId>
    <PackageDescription>SVG raster and video conversion APIs for ConsoleToSvg.</PackageDescription>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ZLogger" Version="2.5.10" />
  </ItemGroup>
</Project>
