<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <PublishAot>false</PublishAot>
    <UseMSBuildTestInfrastructure>true</UseMSBuildTestInfrastructure>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ConsoleToSvg\ConsoleToSvg.csproj" />
    <ProjectReference Include="..\..\src\ConsoleToSvg.Record\ConsoleToSvg.Record.csproj" />
    <None
      Include="..\..\src\ConsoleToSvg.QuickLeaks\QuickLeaks.generation-report.json"
      Link="QuickLeaks.generation-report.json"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
