// <auto-generated />
using System.Text.RegularExpressions;

namespace ConsoleToSvg.QuickLeaks;

public static partial class QuickLeaks
{
    [GeneratedRegex("(?i)(?:droneci)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule128();
    [GeneratedRegex("(?i)(?:droneci)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule128();
    [GeneratedRegex("(?i)(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{15})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule129();
    [GeneratedRegex("(?i)(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,15})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule129();
    [GeneratedRegex("(?i)(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\\-_=]{43})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule130();
    [GeneratedRegex("(?i)(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,11}(AAAAAAAAAA)[a-z0-9\\-_=]{0,43})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule130();
    [GeneratedRegex("(?i)(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{135})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule131();
    [GeneratedRegex("(?i)(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{0,135})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule131();
    [GeneratedRegex("duffel_(?:test|live)_(?i)[a-z0-9_\\-=]{43}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule132();
    [GeneratedRegex("duffel_(?:test|live)_(?i)[a-z0-9_\\-=]{0,43}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule132();
    [GeneratedRegex("dt0c01\\.(?i)[a-z0-9]{24}\\.[a-z0-9]{64}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule133();
    [GeneratedRegex("dt0c01\\.(?i)[a-z0-9]{0,24}\\.[a-z0-9]{0,64}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule133();
    [GeneratedRegex("\\bEZAK(?i)[a-z0-9]{54}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule134();
    [GeneratedRegex("\\bEZAK(?i)[a-z0-9]{0,54}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule134();
    [GeneratedRegex("\\bEZTK(?i)[a-z0-9]{54}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule135();
    [GeneratedRegex("\\bEZTK(?i)[a-z0-9]{0,54}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule135();
    [GeneratedRegex("\\b([a-zA-Z0-9_-]+-[a-zA-Z0-9_-]+-PRD-[a-f0-9]{8,12}-[a-f0-9]{8,12})", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule136();
    [GeneratedRegex("\\b([a-zA-Z0-9_-]+-[a-zA-Z0-9_-]+-PRD-[a-f0-9]{0,12}-[a-f0-9]{0,12})", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule136();
    [GeneratedRegex("(?i:(?:ebay(?:[_. -]*(?:client|api))?[_. -]*(?:secret|key))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(PRD-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4,12})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule137();
    [GeneratedRegex("(?i:(?:ebay(?:[_. -]*(?:client|api))?[_. -]*(?:secret|key))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(PRD-[a-f0-9]{0,8}-[a-f0-9]{0,4}-[a-f0-9]{0,4}-[a-f0-9]{0,4}-[a-f0-9]{0,12})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule137();
    [GeneratedRegex("\\b(essu_[A-Za-z0-9_\\-]{60,200}={0,2})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule138();
    [GeneratedRegex("\\b(essu_[A-Za-z0-9_\\-]{0,200}={0,2})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule138();
    [GeneratedRegex("(?i)(?:elevenlabs)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(sk_[0-9a-f]{48})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule139();
    [GeneratedRegex("(?i)(?:elevenlabs)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(sk_[0-9a-f]{0,48})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule139();
    [GeneratedRegex("(?i)(?:endor(?:labs)?|key)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(endr\\+[A-Za-z0-9-]{16})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule140();
    [GeneratedRegex("(?i)(?:endor(?:labs)?|key)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(endr\\+[A-Za-z0-9-]{0,16})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule140();
    [GeneratedRegex("(?i)(?:endor(?:labs)?|secret)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(endr\\+[A-Za-z0-9-]{16})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule141();
    [GeneratedRegex("(?i)(?:endor(?:labs)?|secret)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(endr\\+[A-Za-z0-9-]{0,16})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule141();
    [GeneratedRegex("(?i)(?:etsy|x-api-key)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{24}:[a-z0-9]{10,64})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule142();
    [GeneratedRegex("(?i)(?:etsy|x-api-key)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,24}:[a-z0-9]{0,64})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule142();
    [GeneratedRegex("\\b(EXO[a-zA-Z0-9]{24,30})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule143();
    [GeneratedRegex("\\b(EXO[a-zA-Z0-9]{0,30})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule143();
    [GeneratedRegex("(?i)(?:exoscale)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([A-Za-z0-9_\\-]{40,60})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule144();
    [GeneratedRegex("(?i)(?:exoscale)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([A-Za-z0-9_\\-]{0,60})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule144();
    [GeneratedRegex("(?i)\\b(\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule145();
    [GeneratedRegex("(?i)\\b(\\d{0,16}(\\||%)[0-9a-z\\-_]{0,40})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule145();
    [GeneratedRegex("\\b(EAA[MC](?i)[a-z0-9]{100,})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule146();
    [GeneratedRegex("\\b(EAA[MC](?i)[a-z0-9]{100,})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule146();
    [GeneratedRegex("(?i)(?:facebook)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule147();
    [GeneratedRegex("(?i)(?:facebook)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{0,32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule147();
    [GeneratedRegex("(?i:(?:falai|fal_ai|fal-ai|fal.ai|fal-api|fal_api|fal_key|fal-key)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}:[a-f0-9]{32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule148();
    [GeneratedRegex("(?i:(?:falai|fal_ai|fal-ai|fal.ai|fal-api|fal_api|fal_key|fal-key)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{0,8}-[a-f0-9]{0,4}-[a-f0-9]{0,4}-[a-f0-9]{0,4}-[a-f0-9]{0,12}:[a-f0-9]{0,32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule148();
    [GeneratedRegex("(?i)(?:fastly)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule149();
    [GeneratedRegex("(?i)(?:fastly)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{0,32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule149();
    [GeneratedRegex("(?i)(?:x-figma-token|xfigmatoken|x_figma_token)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9A-F]{4}-[0-9A-F]{8}(?:-[0-9A-F]{4}){3}-[0-9A-F]{12})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule150();
    [GeneratedRegex("(?i)(?:x-figma-token|xfigmatoken|x_figma_token)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9A-F]{0,4}-[0-9A-F]{0,8}(?:-[0-9A-F]{0,4}){0,3}-[0-9A-F]{0,12})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule150();
    [GeneratedRegex("(?i)\\b(figd_[A-Z0-9_-]{38,42})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule151();
    [GeneratedRegex("(?i)\\b(figd_[A-Z0-9_-]{0,42})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule151();
    [GeneratedRegex("(?i)(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule152();
    [GeneratedRegex("(?i)(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{0,32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule152();
    [GeneratedRegex("(?i)(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule153();
    [GeneratedRegex("(?i)(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,20})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule153();
    [GeneratedRegex("(?i)(?:finnhub)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule154();
    [GeneratedRegex("(?i)(?:finnhub)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,20})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule154();
    [GeneratedRegex("(?i)(?:flickr)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule155();
    [GeneratedRegex("(?i)(?:flickr)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,32})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule155();
    [GeneratedRegex("FLWSECK_TEST-(?i)[a-h0-9]{12}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule156();
    [GeneratedRegex("FLWSECK_TEST-(?i)[a-h0-9]{0,12}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule156();
    [GeneratedRegex("FLWPUBK_TEST-(?i)[a-h0-9]{32}-X", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule157();
    [GeneratedRegex("FLWPUBK_TEST-(?i)[a-h0-9]{0,32}-X", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule157();
    [GeneratedRegex("FLWSECK_TEST-(?i)[a-h0-9]{32}-X", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule158();
    [GeneratedRegex("FLWSECK_TEST-(?i)[a-h0-9]{0,32}-X", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule158();
    [GeneratedRegex("\\b(FlyV1\\s[A-Za-z0-9=_\\-,/+]{100,})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule159();
    [GeneratedRegex("\\b(FlyV1\\s[A-Za-z0-9=_\\-,/+]{100,})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule159();
    [GeneratedRegex("fio-u-(?i)[a-z0-9\\-_=]{64}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule160();
    [GeneratedRegex("fio-u-(?i)[a-z0-9\\-_=]{0,64}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule160();
    [GeneratedRegex("(?i)[\"']secret_key[\"']\\s*=>\\s*[\"'](sk_[\\S]{29})[\"']", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule161();
    [GeneratedRegex("(?i)[\"']secret_key[\"']\\s*=>\\s*[\"'](sk_[\\S]{0,29})[\"']", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule161();
    [GeneratedRegex("(?i)(?:freshbooks)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule162();
    [GeneratedRegex("(?i)(?:freshbooks)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{0,64})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule162();
    [GeneratedRegex("(?i)(?:(?:fullstory|fs_api|fullstory_api))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((?:na1|eu1)\\.[A-Za-z0-9]{20,})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule163();
    [GeneratedRegex("(?i)(?:(?:fullstory|fs_api|fullstory_api))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((?:na1|eu1)\\.[A-Za-z0-9]{20,})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule163();
    [GeneratedRegex("\\b(AIza[\\w-]{35})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule164();
    [GeneratedRegex("\\b(AIza[\\w-]{0,35})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule164();
    [GeneratedRegex("\\{[^{]+(?:(?:\"client_secret\"\\s*:\\s*\"[^\"]+\"[^}]+\"refresh_token\"\\s*:\\s*\"[^\"]+\")|(?:\"refresh_token\"\\s*:\\s*\"[^\"]+\"[^}]+\"client_secret\"\\s*:\\s*\"[^\"]+\"))[^}]+\\}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule165();
    [GeneratedRegex("\\{[^{]+(?:(?:\"client_secret\"\\s*:\\s*\"[^\"]+\"[^}]+\"refresh_token\"\\s*:\\s*\"[^\"]+\")|(?:\"refresh_token\"\\s*:\\s*\"[^\"]+\"[^}]+\"client_secret\"\\s*:\\s*\"[^\"]+\"))[^}]+\\}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule165();
    [GeneratedRegex("\\b(AQ\\.Ab8RN6[A-Za-z0-9_-]{44})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule166();
    [GeneratedRegex("\\b(AQ\\.Ab8RN6[A-Za-z0-9_-]{0,44})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule166();
    [GeneratedRegex("\\{[^{]+(?:(?:\"private_key\"\\s*:\\s*\"-----BEGIN (?:RSA )?PRIVATE KEY-----[^}]+auth_provider_x509_cert_url)|(?:auth_provider_x509_cert_url[^}]+\"private_key\"\\s*:\\s*\"-----BEGIN (?:RSA )?PRIVATE KEY-----))[^}]+\\}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule167();
    [GeneratedRegex("\\{[^{]+(?:(?:\"private_key\"\\s*:\\s*\"-----BEGIN (?:RSA )?PRIVATE KEY-----[^}]+auth_provider_x509_cert_url)|(?:auth_provider_x509_cert_url[^}]+\"private_key\"\\s*:\\s*\"-----BEGIN (?:RSA )?PRIVATE KEY-----))[^}]+\\}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule167();
    [GeneratedRegex("(?i)(?:access|auth|(?-i:[Aa]pi|API)|credential|creds|key|secret|token)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([\\w.=-]{10,150}|[a-z0-9][a-z0-9+/]{11,}={0,3})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule168();
    [GeneratedRegex("(?i)(?:access|auth|(?-i:[Aa]pi|API)|credential|creds|key|secret|token)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([\\w.=-]{0,150}|[a-z0-9][a-z0-9+/]{11,}={0,3})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule168();
    [GeneratedRegex("(?i)\\b(?<uri>(?<scheme>https?|postgres(?:ql)?|mysql|mariadb|mongodb(?:\\+srv)?|rediss?|amqps?|ldaps?|smtps?|ftps?|ssh)://(?<username>[^:/@\\s'\"\\x60]{0,128}):(?<password>[^/@\\s'\"\\x60]{1,256})@(?<host>(?:\\[[0-9a-f:.%]+\\]|[a-z0-9][a-z0-9._-]{0,252}))(?::[0-9]{1,5})?(?:,(?:\\[[0-9a-f:.%]+\\]|[a-z0-9][a-z0-9._-]{0,252})(?::[0-9]{1,5})?)*(?:[/?][a-z0-9._~!$&(*+,;=:@%/?-]*)?)(?:[\\s'\"\\x60#<>{}\\[\\],;)]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule169();
    [GeneratedRegex("(?i)\\b(?<uri>(?<scheme>https?|postgres(?:ql)?|mysql|mariadb|mongodb(?:\\+srv)?|rediss?|amqps?|ldaps?|smtps?|ftps?|ssh)://(?<username>[^:/@\\s'\"\\x60]{0,128}):(?<password>[^/@\\s'\"\\x60]{0,256})@(?<host>(?:\\[[0-9a-f:.%]+\\]|[a-z0-9][a-z0-9._-]{0,252}))(?::[0-9]{0,5})?(?:,(?:\\[[0-9a-f:.%]+\\]|[a-z0-9][a-z0-9._-]{0,252})(?::[0-9]{0,5})?)*(?:[/?][a-z0-9._~!$&(*+,;=:@%/?-]*)?)(?:[\\s'\"\\x60#<>{}\\[\\],;)]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule169();
    [GeneratedRegex("(?i)(?:(?:passw(?:or)?d|psw|[_.-]pw)\\b[ \\t'\"\\\\]{0,3}(?:=>|:=|=|:)[ \\t]{0,5}(?:\"((?:\\\\.|[^\"\\\\\\r\\n]){5,250})\"|'((?:\\\\.|[^'\\\\\\r\\n]){5,250})'|\\x60((?:\\\\.|[^\\x60\\\\\\r\\n]){5,250})\\x60|([^:=\\s'\"\\x60,;][^\\s'\"\\x60,;]{4,249}))(?:[ \\t]*[,;)}\\]\\r\\n]|[ \\t]+(?:#|//|/\\*|--)|[ \\t]*$|\\\\[nr])|\\b(?:login|log_in|authenticate)\\b[ \\t]*\\([ \\t]*[^,()\\r\\n]{1,250}[ \\t]*,[ \\t]*(?:\"((?:\\\\.|[^\"\\\\\\r\\n]){4,250})\"|'((?:\\\\.|[^'\\\\\\r\\n]){4,250})'|\\x60((?:\\\\.|[^\\x60\\\\\\r\\n]){4,250})\\x60)[ \\t]*\\))", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule170();
    [GeneratedRegex("(?i)(?:(?:passw(?:or)?d|psw|[_.-]pw)\\b[ \\t'\"\\\\]{0,3}(?:=>|:=|=|:)[ \\t]{0,5}(?:\"((?:\\\\.|[^\"\\\\\\r\\n]){0,250})\"|'((?:\\\\.|[^'\\\\\\r\\n]){0,250})'|\\x60((?:\\\\.|[^\\x60\\\\\\r\\n]){0,250})\\x60|([^:=\\s'\"\\x60,;][^\\s'\"\\x60,;]{0,249}))(?:[ \\t]*[,;)}\\]\\r\\n]|[ \\t]+(?:#|//|/\\*|--)|[ \\t]*$|\\\\[nr])|\\b(?:login|log_in|authenticate)\\b[ \\t]*\\([ \\t]*[^,()\\r\\n]{1,250}[ \\t]*,[ \\t]*(?:\"((?:\\\\.|[^\"\\\\\\r\\n]){0,250})\"|'((?:\\\\.|[^'\\\\\\r\\n]){0,250})'|\\x60((?:\\\\.|[^\\x60\\\\\\r\\n]){0,250})\\x60)[ \\t]*\\))", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule170();
    [GeneratedRegex("(?m)(?:^|[^a-zA-Z0-9])(?i:username|user|login(?:[_.-]?name)?|email(?:[_.-]?address)?|uid|account(?:[_.-]?name)?|client(?:[_.-]?(?:id|name))?)\\b[ \\t'\"\\\\]{0,3}(?:=>|:=|=|:)[ \\t]{0,5}(?:\"((?:\\\\.|[^\"\\\\\\r\\n]){3,250})\"|'((?:\\\\.|[^'\\\\\\r\\n]){3,250})'|\\x60((?:\\\\.|[^\\x60\\\\\\r\\n]){3,250})\\x60|([^:=\\s'\"\\x60,;][^\\s'\"\\x60,;]{2,249}))(?:[ \\t]*[,;)}\\]\\r\\n]|[ \\t]*$|\\\\[nr])", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule171();
    [GeneratedRegex("(?m)(?:^|[^a-zA-Z0-9])(?i:username|user|login(?:[_.-]?name)?|email(?:[_.-]?address)?|uid|account(?:[_.-]?name)?|client(?:[_.-]?(?:id|name))?)\\b[ \\t'\"\\\\]{0,3}(?:=>|:=|=|:)[ \\t]{0,5}(?:\"((?:\\\\.|[^\"\\\\\\r\\n]){0,250})\"|'((?:\\\\.|[^'\\\\\\r\\n]){0,250})'|\\x60((?:\\\\.|[^\\x60\\\\\\r\\n]){0,250})\\x60|([^:=\\s'\"\\x60,;][^\\s'\"\\x60,;]{0,249}))(?:[ \\t]*[,;)}\\]\\r\\n]|[ \\t]*$|\\\\[nr])", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule171();
    [GeneratedRegex("(?i)(?:gitea[_.-]?(?:token|key|secret|access))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{40})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule172();
    [GeneratedRegex("(?i)(?:gitea[_.-]?(?:token|key|secret|access))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{0,40})(?:\\\\?['\"\\x60]|[\\s;]|\\\\[nr]|$)", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule172();
    [GeneratedRegex("(?:ghu|ghs)_[0-9a-zA-Z]{36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule173();
    [GeneratedRegex("(?:ghu|ghs)_[0-9a-zA-Z]{0,36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule173();
    [GeneratedRegex("github_pat_\\w{82}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule174();
    [GeneratedRegex("github_pat_\\w{0,82}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule174();
    [GeneratedRegex("gho_[0-9a-zA-Z]{36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule175();
    [GeneratedRegex("gho_[0-9a-zA-Z]{0,36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule175();
    [GeneratedRegex("ghp_[0-9a-zA-Z]{36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule176();
    [GeneratedRegex("ghp_[0-9a-zA-Z]{0,36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule176();
    [GeneratedRegex("ghr_[0-9a-zA-Z]{36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule177();
    [GeneratedRegex("ghr_[0-9a-zA-Z]{0,36}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule177();
    [GeneratedRegex("glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule178();
    [GeneratedRegex("glcbt-[0-9a-zA-Z]{0,5}_[0-9a-zA-Z_-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule178();
    [GeneratedRegex("gldt-[0-9a-zA-Z_\\-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule179();
    [GeneratedRegex("gldt-[0-9a-zA-Z_\\-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule179();
    [GeneratedRegex("glffct-[0-9a-zA-Z_\\-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule180();
    [GeneratedRegex("glffct-[0-9a-zA-Z_\\-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule180();
    [GeneratedRegex("glft-[0-9a-zA-Z_\\-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule181();
    [GeneratedRegex("glft-[0-9a-zA-Z_\\-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule181();
    [GeneratedRegex("incoming\\+(?:[A-Za-z0-9._-]+-)?\\d+-([A-Za-z0-9_-]+)-(?:issue(?:-\\d+)?|merge-request)@", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule182();
    [GeneratedRegex("incoming\\+(?:[A-Za-z0-9._-]+-)?\\d+-([A-Za-z0-9_-]+)-(?:issue(?:-\\d+)?|merge-request)@", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule182();
    [GeneratedRegex("glimt-[0-9a-zA-Z_\\-]{25}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule183();
    [GeneratedRegex("glimt-[0-9a-zA-Z_\\-]{0,25}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule183();
    [GeneratedRegex("glagent-[0-9a-zA-Z_\\-]{50}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule184();
    [GeneratedRegex("glagent-[0-9a-zA-Z_\\-]{0,50}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule184();
    [GeneratedRegex("gloas-[0-9a-zA-Z_\\-]{64}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule185();
    [GeneratedRegex("gloas-[0-9a-zA-Z_\\-]{0,64}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule185();
    [GeneratedRegex("glpat-[\\w-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule186();
    [GeneratedRegex("glpat-[\\w-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule186();
    [GeneratedRegex("\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule187();
    [GeneratedRegex("\\bglpat-[0-9a-zA-Z_-]{0,300}\\.[0-9a-z]{0,2}[0-9a-z]{0,7}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule187();
    [GeneratedRegex("\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}\\.[0-9a-z]{9}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule188();
    [GeneratedRegex("\\bglpat-[0-9a-zA-Z_-]{0,300}\\.[0-9a-z]{0,2}\\.[0-9a-z]{0,9}\\b", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule188();
    [GeneratedRegex("glptt-[0-9a-f]{40}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule189();
    [GeneratedRegex("glptt-[0-9a-f]{0,40}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule189();
    [GeneratedRegex("GR1348941[\\w-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule190();
    [GeneratedRegex("GR1348941[\\w-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule190();
    [GeneratedRegex("glrt-[0-9a-zA-Z_\\-]{20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex Rule191();
    [GeneratedRegex("glrt-[0-9a-zA-Z_\\-]{0,20}", RegexOptions.CultureInvariant, MatchTimeoutMilliseconds)]
    private static partial Regex EarlyRule191();
}
