<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <PackageId>ConsoleToSvg</PackageId>
    <ToolCommandName>console2svg</ToolCommandName>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <RollForward>LatestMajor</RollForward>
    <PackageDescription>.NET tool launcher for the ConsoleToSvg NativeAOT binary.</PackageDescription>
    <PackageProjectUrl>https://github.com/arika0093/ConsoleToSvg</PackageProjectUrl>
    <RepositoryUrl>https://github.com/arika0093/ConsoleToSvg</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>arika0093</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NBGV_ThisAssemblyIncludesPackageVersion>true</NBGV_ThisAssemblyIncludesPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
