import { fileURLToPath } from 'node:url';

export function syncDocs() {
  // Assets are committed under docs-site/public/assets and generated by the
  // repository's batch-markdown workflow. Keep this hook for npm scripts.
}

if (process.argv[1] === fileURLToPath(import.meta.url)) syncDocs();
